#! /bin/bash
cd /usr/local/epics/cams-ioc
hn=`hostname`
head=`redis-cli hget config.${hn,,} HEAD`
sn=`redis-cli hget ${head}.config.shortname VALUE`
/usr/local/epics/synApps_5_8/support/areaDetector/ADProsilica/iocs/prosilicaIOC/bin/linux-x86_64/prosilicaApp st-${sn}.cmd
